/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. HEX COLOR 0a7e00
 */
package Presentacion;

import Logica.ConectarBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yojhan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null); //Ubica ventana en la mitad de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_Bici = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JDConductores = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRegistrarConductor = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnEditarConductor = new javax.swing.JButton();
        btnEliminarConductor = new javax.swing.JButton();
        btnAtrasConductor = new javax.swing.JButton();
        txtIdConductor = new javax.swing.JTextField();
        txtCedulaConductor = new javax.swing.JTextField();
        txtNombreConductor = new javax.swing.JTextField();
        txtEdadConductor = new javax.swing.JTextField();
        txtTelefonoConductor = new javax.swing.JTextField();
        txtDireccionConductor = new javax.swing.JTextField();
        txtContrasenaConductor = new javax.swing.JTextField();
        btnBuscarConductor = new javax.swing.JButton();
        panel_logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_datos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_correo = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        panel_buses = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panel_transfers = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panel_biciagil = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_clientes = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel_conductores = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        jDialog_Bici.setTitle("Bici-ágil");
        jDialog_Bici.setMinimumSize(new java.awt.Dimension(300, 200));

        jButton1.setText("Ver bicicletas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reservar bicicleta");

        javax.swing.GroupLayout jDialog_BiciLayout = new javax.swing.GroupLayout(jDialog_Bici.getContentPane());
        jDialog_Bici.getContentPane().setLayout(jDialog_BiciLayout);
        jDialog_BiciLayout.setHorizontalGroup(
            jDialog_BiciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_BiciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog_BiciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog_BiciLayout.setVerticalGroup(
            jDialog_BiciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_BiciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JDConductores.setMinimumSize(new java.awt.Dimension(500, 600));

        jLabel8.setText("SECCION CONDUCTORES");

        jLabel9.setText("Id:");

        jLabel10.setText("Cedula:");

        btnRegistrarConductor.setText("Registrar");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Edad:");

        jLabel18.setText("Telefono:");

        jLabel19.setText("Direccion:");

        jLabel20.setText("Contraseña:");

        btnEditarConductor.setText("Editar");

        btnEliminarConductor.setText("Eliminar");

        btnAtrasConductor.setText("Atras");
        btnAtrasConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasConductorActionPerformed(evt);
            }
        });

        txtEdadConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadConductorActionPerformed(evt);
            }
        });

        btnBuscarConductor.setText("Buscar");
        btnBuscarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JDConductoresLayout = new javax.swing.GroupLayout(JDConductores.getContentPane());
        JDConductores.getContentPane().setLayout(JDConductoresLayout);
        JDConductoresLayout.setHorizontalGroup(
            JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDConductoresLayout.createSequentialGroup()
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JDConductoresLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JDConductoresLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(32, 32, 32)
                                .addComponent(txtTelefonoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JDConductoresLayout.createSequentialGroup()
                                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(37, 37, 37)
                                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCedulaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JDConductoresLayout.createSequentialGroup()
                                        .addComponent(txtIdConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(btnBuscarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(JDConductoresLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtContrasenaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JDConductoresLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(31, 31, 31)
                                .addComponent(txtDireccionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JDConductoresLayout.createSequentialGroup()
                                .addComponent(btnRegistrarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(btnAtrasConductor))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JDConductoresLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JDConductoresLayout.setVerticalGroup(
            JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDConductoresLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarConductor))
                .addGap(22, 22, 22)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCedulaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEdadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTelefonoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDireccionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtContrasenaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(JDConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarConductor)
                    .addComponent(btnEditarConductor)
                    .addComponent(btnEliminarConductor)
                    .addComponent(btnAtrasConductor))
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Módulo Administrador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        panel_logo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_logo.setAlignmentX(0.2F);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Sistema de Transporte Público Integrado");

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(panel_logoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_logoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Bienvenido(a):  ");

        label_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_nombre.setText("Nombre administrador ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mis datos");

        jLabel5.setText("Correo: ");

        jLabel6.setText("Nombre de usuario:");

        label_correo.setText("correo electronico");

        label_username.setText("nombre de usuario");

        javax.swing.GroupLayout panel_datosLayout = new javax.swing.GroupLayout(panel_datos);
        panel_datos.setLayout(panel_datosLayout);
        panel_datosLayout.setHorizontalGroup(
            panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosLayout.createSequentialGroup()
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nombre))
                    .addGroup(panel_datosLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_correo)
                            .addComponent(label_username)))
                    .addGroup(panel_datosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panel_datosLayout.setVerticalGroup(
            panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(label_correo))
                .addGap(18, 18, 18)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(label_username))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel_buses.setBackground(new java.awt.Color(234, 234, 234));
        panel_buses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_buses.setMaximumSize(new java.awt.Dimension(111, 104));
        panel_buses.setMinimumSize(new java.awt.Dimension(111, 104));
        panel_buses.setPreferredSize(new java.awt.Dimension(111, 104));
        panel_buses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_busesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_busesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_busesMouseExited(evt);
            }
        });

        jLabel11.setText("Buses");

        javax.swing.GroupLayout panel_busesLayout = new javax.swing.GroupLayout(panel_buses);
        panel_buses.setLayout(panel_busesLayout);
        panel_busesLayout.setHorizontalGroup(
            panel_busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panel_busesLayout.setVerticalGroup(
            panel_busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_busesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        panel_transfers.setBackground(new java.awt.Color(234, 234, 234));
        panel_transfers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_transfers.setMaximumSize(new java.awt.Dimension(111, 104));
        panel_transfers.setMinimumSize(new java.awt.Dimension(111, 104));
        panel_transfers.setPreferredSize(new java.awt.Dimension(111, 104));
        panel_transfers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_transfersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_transfersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_transfersMouseExited(evt);
            }
        });

        jLabel12.setText("Transfer");

        javax.swing.GroupLayout panel_transfersLayout = new javax.swing.GroupLayout(panel_transfers);
        panel_transfers.setLayout(panel_transfersLayout);
        panel_transfersLayout.setHorizontalGroup(
            panel_transfersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_transfersLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(31, 31, 31))
        );
        panel_transfersLayout.setVerticalGroup(
            panel_transfersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_transfersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        panel_biciagil.setBackground(new java.awt.Color(234, 234, 234));
        panel_biciagil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_biciagil.setMaximumSize(new java.awt.Dimension(111, 104));
        panel_biciagil.setMinimumSize(new java.awt.Dimension(111, 104));
        panel_biciagil.setPreferredSize(new java.awt.Dimension(111, 104));
        panel_biciagil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_biciagilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_biciagilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_biciagilMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("Bici-ágil");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ion-android-bicycle.png"))); // NOI18N

        javax.swing.GroupLayout panel_biciagilLayout = new javax.swing.GroupLayout(panel_biciagil);
        panel_biciagil.setLayout(panel_biciagilLayout);
        panel_biciagilLayout.setHorizontalGroup(
            panel_biciagilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_biciagilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(35, 35, 35))
            .addGroup(panel_biciagilLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panel_biciagilLayout.setVerticalGroup(
            panel_biciagilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_biciagilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        panel_clientes.setBackground(new java.awt.Color(234, 234, 234));
        panel_clientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_clientes.setMaximumSize(new java.awt.Dimension(111, 104));
        panel_clientes.setMinimumSize(new java.awt.Dimension(111, 104));
        panel_clientes.setPreferredSize(new java.awt.Dimension(111, 104));
        panel_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_clientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_clientesMouseExited(evt);
            }
        });

        jLabel14.setText("Clientes");

        javax.swing.GroupLayout panel_clientesLayout = new javax.swing.GroupLayout(panel_clientes);
        panel_clientes.setLayout(panel_clientesLayout);
        panel_clientesLayout.setHorizontalGroup(
            panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_clientesLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(33, 33, 33))
        );
        panel_clientesLayout.setVerticalGroup(
            panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_clientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        panel_conductores.setBackground(new java.awt.Color(234, 234, 234));
        panel_conductores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_conductores.setMaximumSize(new java.awt.Dimension(111, 104));
        panel_conductores.setMinimumSize(new java.awt.Dimension(111, 104));
        panel_conductores.setPreferredSize(new java.awt.Dimension(111, 104));
        panel_conductores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_conductoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_conductoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_conductoresMouseExited(evt);
            }
        });

        jLabel15.setText("Conductores");

        javax.swing.GroupLayout panel_conductoresLayout = new javax.swing.GroupLayout(panel_conductores);
        panel_conductores.setLayout(panel_conductoresLayout);
        panel_conductoresLayout.setHorizontalGroup(
            panel_conductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_conductoresLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(21, 21, 21))
        );
        panel_conductoresLayout.setVerticalGroup(
            panel_conductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_conductoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_conductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_buses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_transfers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_biciagil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_buses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_transfers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_biciagil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_conductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_biciagilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_biciagilMouseClicked
       this.jDialog_Bici.setVisible(true);
       jDialog_Bici.setLocationRelativeTo(null); //Ubica ventana en la mitad de la pantalla
    }//GEN-LAST:event_panel_biciagilMouseClicked

    private void panel_conductoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_conductoresMouseClicked
        // TODO add your handling code here:
        
        this.JDConductores.show();
    }//GEN-LAST:event_panel_conductoresMouseClicked

    private void panel_busesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_busesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_busesMouseClicked

    private void panel_transfersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_transfersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_transfersMouseClicked

    private void panel_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_clientesMouseClicked

    private void panel_biciagilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_biciagilMouseEntered
        panel_biciagil.setBackground(new Color(248,248,248));
    }//GEN-LAST:event_panel_biciagilMouseEntered

    private void panel_biciagilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_biciagilMouseExited
         panel_biciagil.setBackground(new Color(234,234,234));
    }//GEN-LAST:event_panel_biciagilMouseExited

    private void panel_conductoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_conductoresMouseEntered
        panel_conductores.setBackground(new Color(248,248,248));
    }//GEN-LAST:event_panel_conductoresMouseEntered

    private void panel_conductoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_conductoresMouseExited
       panel_conductores.setBackground(new Color(234,234,234));
    }//GEN-LAST:event_panel_conductoresMouseExited

    private void panel_busesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_busesMouseEntered
        panel_buses.setBackground(new Color(248,248,248));
    }//GEN-LAST:event_panel_busesMouseEntered

    private void panel_busesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_busesMouseExited
        panel_buses.setBackground(new Color(234,234,234));
    }//GEN-LAST:event_panel_busesMouseExited

    private void panel_transfersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_transfersMouseEntered
       panel_transfers.setBackground(new Color(248,248,248));
    }//GEN-LAST:event_panel_transfersMouseEntered

    private void panel_transfersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_transfersMouseExited
       panel_transfers.setBackground(new Color(234,234,234));
    }//GEN-LAST:event_panel_transfersMouseExited

    private void panel_clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clientesMouseEntered
        panel_clientes.setBackground(new Color(248,248,248));
    }//GEN-LAST:event_panel_clientesMouseEntered

    private void panel_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clientesMouseExited
       panel_clientes.setBackground(new Color(234,234,234));
    }//GEN-LAST:event_panel_clientesMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEdadConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadConductorActionPerformed

    private void btnBuscarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConductorActionPerformed
           try { 
            
               ConectarBD conexion=new ConectarBD(); 
                Statement sentencia; 
                
            sentencia=conexion.getConexion().createStatement(); 
            ResultSet resultado=sentencia.executeQuery("select * from CONDUCTOR where CONDUCTOR_ID ="
                    +Integer.parseInt(this.txtIdConductor.getText())); 
            
           while (resultado.next())
            {
                this.txtCedulaConductor.setText(""+resultado.getString("CEDULA"));
                this.txtNombreConductor.setText(""+resultado.getString("NOMBRE"));
                this.txtEdadConductor.setText(""+resultado.getString("EDAD"));
                this.txtTelefonoConductor.setText(""+resultado.getString("TELEFONO"));
                this.txtDireccionConductor.setText(""+resultado.getString("DIRECCION"));
                this.txtContrasenaConductor.setText(""+resultado.getString("CONTRASEÑA"));

            }
     
        resultado.close();
        conexion.getConexion().close();
        }
             catch(SQLException e ) 
                { 
                    JOptionPane.showMessageDialog(this,"Error SQL:"+e,"Información" 
                    ,JOptionPane.INFORMATION_MESSAGE); 
              
                } 
                    catch(Exception e) 
                       { 
                        JOptionPane.showMessageDialog(this,"Error:"+e,"Información" 
                        ,JOptionPane.INFORMATION_MESSAGE);
                        
                       }
    }//GEN-LAST:event_btnBuscarConductorActionPerformed

    private void btnAtrasConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasConductorActionPerformed
        // TODO add your handling code here:
        
        this.JDConductores.hide();
    }//GEN-LAST:event_btnAtrasConductorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDConductores;
    private javax.swing.JButton btnAtrasConductor;
    private javax.swing.JButton btnBuscarConductor;
    private javax.swing.JButton btnEditarConductor;
    private javax.swing.JButton btnEliminarConductor;
    private javax.swing.JButton btnRegistrarConductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog_Bici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_correo;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel panel_biciagil;
    private javax.swing.JPanel panel_buses;
    private javax.swing.JPanel panel_clientes;
    private javax.swing.JPanel panel_conductores;
    private javax.swing.JPanel panel_datos;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_transfers;
    private javax.swing.JTextField txtCedulaConductor;
    private javax.swing.JTextField txtContrasenaConductor;
    private javax.swing.JTextField txtDireccionConductor;
    private javax.swing.JTextField txtEdadConductor;
    private javax.swing.JTextField txtIdConductor;
    private javax.swing.JTextField txtNombreConductor;
    private javax.swing.JTextField txtTelefonoConductor;
    // End of variables declaration//GEN-END:variables
}
